// Command docgen generates the shell completions and man pages that are bundled
// into release archives (and installed by the Homebrew formula). It is a
// build-time tool only — it is never compiled into the vibexp binary, so the
// `go install github.com/vibexp/cli/cmd/vibexp@latest` path stays free of its
// extra dependencies (cobra/doc, go-md2man).
//
// Usage: go run ./cmd/docgen [output-dir]   (output-dir defaults to ".")
//
// It writes:
//
//	<output-dir>/completions/vibexp.{bash,zsh,fish,ps1}
//	<output-dir>/manpages/vibexp*.1
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/vibexp/cli/internal/cli"
	"github.com/vibexp/cli/internal/version"
)

func main() {
	outDir := "."
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}
	if err := run(outDir); err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	root := cli.NewRootCommand(cli.Options{})
	// Reproducible output: never stamp the generation date into the man pages.
	disableAutoGenTag(root)

	completionsDir := filepath.Join(outDir, "completions")
	manDir := filepath.Join(outDir, "manpages")
	for _, d := range []string{completionsDir, manDir} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}

	if err := genCompletions(root, completionsDir); err != nil {
		return fmt.Errorf("completions: %w", err)
	}
	if err := genManPages(root, manDir); err != nil {
		return fmt.Errorf("man pages: %w", err)
	}
	return nil
}

// genCompletions writes a completion script per supported shell.
func genCompletions(root *cobra.Command, dir string) error {
	if err := root.GenBashCompletionFileV2(filepath.Join(dir, "vibexp.bash"), true); err != nil {
		return err
	}
	if err := root.GenZshCompletionFile(filepath.Join(dir, "vibexp.zsh")); err != nil {
		return err
	}
	if err := root.GenFishCompletionFile(filepath.Join(dir, "vibexp.fish"), true); err != nil {
		return err
	}
	return root.GenPowerShellCompletionFileWithDesc(filepath.Join(dir, "vibexp.ps1"))
}

// genManPages writes a section-1 man page for the root command and every
// subcommand.
func genManPages(root *cobra.Command, dir string) error {
	header := &doc.GenManHeader{
		Title:   "VIBEXP",
		Section: "1",
		Source:  "vibexp " + version.Version,
		Manual:  "VibeXP CLI Manual",
	}
	return doc.GenManTree(root, header, dir)
}

// disableAutoGenTag turns off cobra's "Auto generated by spf13/cobra on <date>"
// footer for the whole command tree so man-page output is byte-stable.
func disableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, c := range cmd.Commands() {
		disableAutoGenTag(c)
	}
}
